const SAVE_USER_INFO = 'SAVE_USER_INFO'
const UPDATE_ARTICLES = 'UPDATE_ARTICLES'
const UPDATE_ID_PAGINATION = 'UPDATE_ID_PAGINATION'
const ADD_ARTICLES_ERROR = 'ADD_ARTICLES_ERROR'
const SET_TAGS = 'SET_TAGS'
const SET_AUTH = 'SET_AUTH'
const DELETE_USER_INFO = 'DELETE_USER_INFO'
const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE'
const UPDATE_ARTICLES_API = 'UPDATE_ARTICLES_API'
const SET_NEW_ARTICLE = 'SET_NEW_ARTICLE'
const GET_ARTICLE_INFO = 'GET_ARTICLE_INFO'
const GET_COMMENTS = 'GET_COMMENTS'
const DEL_COMMENTS = 'DEL_COMMENTS'
const SET_COMMENT = 'SET_COMMENT;'
const DELETE_ARTICLES = 'DELETE_ARTICLES'
const EDIT_MODE = 'EDIT_MODE'
const SET_TAG = 'SET_TAG'
const SET_AUTH_TAG = 'SET_AUTH_TAG'
const CLEAN_FORM_NEW_ARTICLE = 'CLEAN_FORM_NEW_ARTICLE'
const CLEAN_ERROR = 'CLEAN_ERROR'
const REGISTER_ERROR = 'REGISTER_ERROR'

export {
  SAVE_USER_INFO,
  UPDATE_ARTICLES,
  UPDATE_ID_PAGINATION,
  ADD_ARTICLES_ERROR,
  SET_TAGS,
  SET_AUTH,
  DELETE_USER_INFO,
  SAVE_USER_PROFILE,
  UPDATE_ARTICLES_API,
  SET_NEW_ARTICLE,
  GET_ARTICLE_INFO,
  GET_COMMENTS,
  DEL_COMMENTS,
  SET_COMMENT,
  DELETE_ARTICLES,
  EDIT_MODE,
  SET_TAG,
  SET_AUTH_TAG,
  CLEAN_FORM_NEW_ARTICLE,
  CLEAN_ERROR,
  REGISTER_ERROR
}